code/routes/admin.php
<?php

Route::get('/logout', function () {
    \Auth::logout();
    return redirect()->route('home');
});

Route::get('/company-dublicates', function () {
    $companies = DB::table("companies")
        ->select(DB::raw('count(*) as count, name'))
        ->where('active', true)
        ->where('moderated', false)
        ->groupBy('name')
        ->having('count', '>', 1)
        ->limit(1000)
        ->get();

    foreach ($companies as $company) {
        echo $company->name . "<br>";
    }
    exit();
});

Route::get('/company-with-comments', function () {
    $items = DB::select("SELECT
  comment_threads.title,
  count(comments.thread_id),
  comments.thread_id
FROM comment_threads

  JOIN comments ON comment_threads.id = comments.thread_id
  JOIN companies
    ON companies.id = comment_threads.commentable_id

WHERE companies.moderated = FALSE
GROUP BY thread_id;");

    foreach ($items as $item) {
        echo $item->title . "<br>";
    }
    exit();
});


Route::get('api/service', 'Api\ServiceController@index');
Route::post('api/service/parse', 'Api\ServiceController@parse');
Route::get('api/user', 'Api\UserController@index');
Route::get('api/user/{id}', 'Api\UserController@show');
Route::get('api/c-thread', 'Api\CommentThreadController@index');
Route::get('api/c-thread/{id}', 'Api\CommentThreadController@show');


CRUD::resource('permission', 'PermissionCrudController');
CRUD::resource('role', 'RoleCrudController');
CRUD::resource('user', 'UserCrudController');

CRUD::resource('company', 'CompanyCrudController');
CRUD::resource('company-category', 'CompanyCategoryCrudController');
CRUD::resource('company-master-category', 'CompanyMasterCategoryCrudController');
CRUD::resource('service', 'CompanyServiceCrudController');
CRUD::resource('grabber-record', 'GrabberRecordCrudController');

CRUD::resource('setting', 'SettingCrudController');
CRUD::resource('text-block', 'TextBlockCrudController');
CRUD::resource('page', 'PageCrudController');

CRUD::resource('c-thread', 'CommentThreadCrudController');
CRUD::resource('comment', 'CommentCrudController');

code/routes/web.php
<?php

Auth::routes();
Route::view('/register/success', 'auth.register_success');
Route::get('/register/{hash}', [
    'as' => 'user_activation',
    'uses' => 'Auth\RegisterController@activateUser',
])->where('hash', '[0-9a-w]{32}');


Route::get('/', 'WelcomeController@showWelcome')->name('welcome');
Route::get('/home', 'HomeController@index')->name('home');


Route::group(
    [
        'as' => 'companies.',
        'prefix' => 'companies',
    ],
    function () {
        Route::get('/', [
            'as' => 'list',
            'uses' => 'CompaniesController@showCompaniesList',
        ]);

        Route::get('/services', [
            'as' => 'services',
            'uses' => 'CompaniesController@showServices',
        ]);

        Route::get('/services/{name}', [
            'as' => 'service',
            'uses' => 'CompaniesController@showCompaniesByService',
        ]);

        Route::get('/categories', [
            'as' => 'categories',
            'uses' => 'CompaniesController@showCategories',
        ]);

        Route::get('/categories/{name}', [
            'as' => 'category',
            'uses' => 'CompaniesController@showCompaniesByCategory',
        ]);

        Route::get('/{name}', [
            'as' => 'company',
            'uses' => 'CompaniesController@showCompany',
        ]);
    }
);


Route::group(
    [
        'as' => 'profile.',
        'prefix' => 'profile',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', [
            'as' => 'dashboard',
            'uses' => 'ProfileController@showDashboard',
        ]);


        Route::group(
            [
                'as' => 'companies.',
                'prefix' => 'companies',
            ],
            function () {
                Route::get('/', [
                    'as' => 'list',
                    'uses' => 'ProfileController@showCompaniesList',
                ]);

                Route::get('/create', [
                    'as' => 'create-form',
                    'uses' => 'ProfileController@showCompanyCreateForm',
                ]);

                Route::get('/{company_id}/edit', [
                    'as' => 'edit-form',
                    'uses' => 'ProfileController@showCompanyEditForm',
                ])->where('company_id', '[0-9]+');
            }
        );


        Route::get('/user', [
            'as' => 'user',
            'uses' => 'ProfileController@showUserForm',
        ]);
//        Route::post('/user', [
//            'as' => 'user',
//            'uses' => 'ProfileController@updateUser',
//        ]);

        Route::get('/password', [
            'as' => 'password',
            'uses' => 'ProfileController@showUserPasswordForm',
        ]);
//        Route::post('/password', [
//            'as' => 'password',
//            'uses' => 'ProfileController@updateUserPassword',
//        ]);

        Route::get('/notify', [
            'as' => 'notify',
            'uses' => 'ProfileController@showUserNotifyForm',
        ]);
//        Route::post('/notify', [
//            'as' => 'notify',
//            'uses' => 'ProfileController@updateUserNotify',
//        ]);
    }
);


Route::get('/search', [
    'as' => 'search',
    'uses' => 'SearchController@showList',
]);


Route::get('{url}', [
    'uses' => 'PageController@showPage'
])->where('url', '^((?!_debugbar)(?!admin).)*');

code/resources/views/layouts/parts/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="columns">
            <div class="column is-narrow">
                <strong class="footer__site-name">
                    houserepair.info © {{ date("Y") }}
                </strong>

                <ul>
                    <li>
                        <a href="">
                            Условия использования
                        </a>
                    </li>
                    <li>
                        <a href="mailto:help@houserepair.info">
                            help@houserepair.info
                        </a>
                    </li>
                </ul>
            </div>

            <div class="column is-hidden-mobile">
                <div class="columns is-desktop">
                    <div class="column is-narrow footer__categories">
                        {!! $content->getText("footer: links block #1") !!}
                    </div>

                    <div class="column is-narrow footer__categories">
                        {!! $content->getText("footer: links block #2") !!}
                    </div>
                </div>
            </div>


            <div class="column is-4">
                <form action="{{ route('search') }}" class="footer__search-form">
                    <div class="field has-addons">
                        <div class="control is-expanded">
                            <input class="input is-small" name="q" type="text"
                                   placeholder="Название компании или услуги">
                        </div>
                        <div class="control">
                            <button type="submit" class="button is-info is-small">
                                поиск
                            </button>
                        </div>
                    </div>
                </form>

                <p>
                    Информация носит исключительно ознакомительный характер и не является публичной офертой.
                </p>
            </div>
        </div>
    </div>
</footer>

code/resources/views/layouts/parts/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <link href="/static/build/styles.css?v=5" rel="stylesheet">


    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e8d100">
    <meta name="theme-color" content="#ffffff">


    {!! SEOMeta::generate() !!}
    {!! OpenGraph::generate() !!}
    {!! Twitter::generate() !!}

    <link href="https://fonts.googleapis.com/css?family=Exo+2:400,400i,700,700i|Oswald:700" rel="stylesheet">
    <meta name="google-site-verification" content="prH8O9k9vhGa8iybRWLdNLmqQm44k4QO4Xahlt6ESbw"/>
    <meta name="csrf-token" value="{{ csrf_token() }}" content="{{ csrf_token() }}" id="token">


    <style>
        [v-cloak] {
            display: none;
        }
    </style>
</head>

code/resources/views/layouts/parts/scripts.blade.php
<script src="/static/build/app.js?v=5" type="text/javascript"></script>

@if(app('env') == "production")
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function () {
                try {
                    w.yaCounter45926967 = new Ya.Metrika2({
                        id: 45926967,
                        clickmap: true,
                        trackLinks: true,
                        accurateTrackBounce: true,
                        webvisor: true
                    });
                } catch (e) {
                }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () {
                    n.parentNode.insertBefore(s, n);
                };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/tag.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else {
                f();
            }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript>
        <div><img src="https://mc.yandex.ru/watch/45926967" style="position:absolute; left:-9999px;" alt=""/></div>
    </noscript>
    <!-- /Yandex.Metrika counter -->


    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110358798-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-110358798-1');
    </script>
@endif

code/resources/views/layouts/parts/top-nav.blade.php
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">

        <div class="navbar-brand">
            <a class="navbar-item" href="{{ url("/") }}">
                <span class="navbar__logo">
                    house<span>repair</span>.info
                </span>
            </a>

            <burger-menu v-cloak>
                <div slot="main-links">
                    <a class="navbar-item" href="{{ route('companies.list') }}">
                        компании
                    </a>
                    <a class="navbar-item" href="{{ route('companies.categories') }}">
                        разделы
                    </a>
                    <a class="navbar-item" href="{{ route('companies.services') }}">
                        услуги
                    </a>
                </div>

                <div slot="subitems">
                    @if(auth()->check())
                        <a href="" class="">
                            {{ auth()->user()->name }}
                        </a>

                        <a href="{{ route('logout') }}"
                           class=""
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            выход
                        </a>
                    @else
                        <a class="button is-small is-primary is-outlined" href="{{ route('login') }}">
                            <span class="icon">
                                <svg class="navbar__link-icon">
                                    <use xlink:href="#user-auth"></use>
                                </svg>
                            </span>

                            <span>
                                Вход
                            </span>
                        </a>


                        <a class="button is-small is-primary is-outlined" href="{{ route('register') }}">
                            <span class="icon">
                                <svg class="navbar__link-icon">
                                    <use xlink:href="#user-reg"></use>
                                </svg>
                            </span>

                            <span>
                                Регистрация
                            </span>
                        </a>
                    @endif
                </div>
            </burger-menu>
        </div>


        <div class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ route('companies.list') }}">
                    компании
                </a>
                <a class="navbar-item" href="{{ route('companies.categories') }}">
                    разделы
                </a>
                <a class="navbar-item" href="{{ route('companies.services') }}">
                    услуги
                </a>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    @if(auth()->check())
                        <a href="{{ route('profile.dashboard') }}" class="navbar__user-name">
                            {{ auth()->user()->name }}
                        </a>

                        <a href="{{ route('logout') }}"
                           class="navbar__logout"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            выход
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    @else
                        <div class="field is-grouped">


                            <p class="control">
                                <a class="button is-small is-primary is-outlined" href="{{ route('login') }}">
                                    <span class="icon">
                                        <svg class="navbar__link-icon">
                                            <use xlink:href="#user-auth"></use>
                                        </svg>
                                    </span>

                                    <span>
                                        Вход
                                    </span>
                                </a>
                            </p>

                            <p class="control">
                                <a class="button is-small is-primary is-outlined" href="{{ route('register') }}">
                                    <span class="icon">
                                        <svg class="navbar__link-icon">
                                            <use xlink:href="#user-reg"></use>
                                        </svg>
                                    </span>

                                    <span>
                                        Регистрация
                                    </span>
                                </a>
                            </p>
                        </div>
                    @endif
                </div>
            </div>
        </div>

    </div>
</nav>

code/resources/views/layouts/parts/top_nav.blade.php
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">

        <div class="navbar-brand">
            <a class="navbar-item" href="{{ url("/") }}">
                <span class="navbar__logo">
                    house<span>repair</span>.info
                </span>
            </a>

            <burger-menu v-cloak>
                <div slot="main-links">
                    <a class="navbar-item" href="{{ route('companies.list') }}">
                        компании
                    </a>
                    <a class="navbar-item" href="{{ route('companies.categories') }}">
                        разделы
                    </a>
                    <a class="navbar-item" href="{{ route('companies.services') }}">
                        услуги
                    </a>
                </div>

                <div slot="subitems">
                    @if(auth()->check())
                        <a href="" class="">
                            {{ auth()->user()->name }}
                        </a>

                        <a href="{{ route('logout') }}"
                           class=""
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            выход
                        </a>
                    @else
                        <a class="button is-small is-primary is-outlined" href="{{ route('login') }}">
                            <span class="icon">
                                <svg class="navbar__link-icon">
                                    <use xlink:href="#user-auth"></use>
                                </svg>
                            </span>

                            <span>
                                Вход
                            </span>
                        </a>


                        <a class="button is-small is-primary is-outlined" href="{{ route('register') }}">
                            <span class="icon">
                                <svg class="navbar__link-icon">
                                    <use xlink:href="#user-reg"></use>
                                </svg>
                            </span>

                            <span>
                                Регистрация
                            </span>
                        </a>
                    @endif
                </div>
            </burger-menu>
        </div>


        <div class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ route('companies.list') }}">
                    компании
                </a>
                <a class="navbar-item" href="{{ route('companies.categories') }}">
                    разделы
                </a>
                <a class="navbar-item" href="{{ route('companies.services') }}">
                    услуги
                </a>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    @if(auth()->check())
                        <a href="" class="navbar__user-name">
                            {{ auth()->user()->name }}
                        </a>

                        <a href="{{ route('logout') }}"
                           class="navbar__logout"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            выход
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    @else
                        <div class="field is-grouped">


                            <p class="control">
                                <a class="button is-small is-primary is-outlined" href="{{ route('login') }}">
                                    <span class="icon">
                                        <svg class="navbar__link-icon">
                                            <use xlink:href="#user-auth"></use>
                                        </svg>
                                    </span>

                                    <span>
                                        Вход
                                    </span>
                                </a>
                            </p>

                            <p class="control">
                                <a class="button is-small is-primary is-outlined" href="{{ route('register') }}">
                                    <span class="icon">
                                        <svg class="navbar__link-icon">
                                            <use xlink:href="#user-reg"></use>
                                        </svg>
                                    </span>

                                    <span>
                                        Регистрация
                                    </span>
                                </a>
                            </p>
                        </div>
                    @endif
                </div>
            </div>
        </div>

    </div>
</nav>